site_name: GenAI Docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - API Reference: api.md
