site_name: GenAI Docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
- Foundations:
  - Introduction: foundations/intro.md
  - LLMs: foundations/LLMs.md
  - Prompt Engineering Basics: foundations/prompt_engineering.md
  - Tools Overview: foundations/tools_overview.md
  